### ISSUE TITLE
Unable to run without root

### ISSUE THREAD

**Issue by cmh716** [dniklewicz/UPSPowerHelper#1]
Hi, I just bought and installed UPS Power Monitor for Mac and it's talking to my NUT server fine.  I installed the power guard via the script and it fails to run because it says the port is already in use (but it's not).  I attempted to start it manually via:

$ /usr/bin/python3 /Users/cmh716/.upspowerhelper/upspowerhelper.py -p 58879
Traceback (most recent call last):
  File "/Users/cmh716/.upspowerhelper/upspowerhelper.py", line 51, in <module>
    httpd = HTTPServer(server_address, S)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/socketserver.py", line 452, in __init__
    self.server_bind()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/http/server.py", line 138, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 48] Address already in use

If I run this via sudo it works and binds to 58879 and UPS Power Monitor can communicate with localhost.  Do you have any ideas why this non-root user cannot start this server?

**Comment by cmh716** [comment]
I closed UPS Power Monitor and did: sudo lsof -i:58879
Nothing shows up but I still get the error.  But I had no problem starting the server on 48879 (as non-root( so I just altered the plist and restarted the agent and it's working.  Seems like there is some sort of port reservation or something.

**Comment by cmh716** [comment]
<img width="413" alt="Screen Shot 2022-06-07 at 5 11 12 PM" src="https://user-images.githubusercontent.com/3275478/172483491-0d9a59ee-3baf-4f4d-83e5-f27a92cda009.png">

**Comment by dniklewicz** [comment]
Hi!
Part of the installation script is responsible for launching the script in background. If there were no errors during the installation, then the service should be already active and a blocked port is an expected behaviour. To verify if the tool is running on the default port, you can open `http://127.0.0.1:58879/info` in a web browser and check if a JSON response is returned.

**Comment by cmh716** [comment]
yes, after installation the agent was inactive after installation due to this port issue.  We can close this issue because it's working on another port. thanks
